import { Router } from 'express';
import * as controller from '../controllers/projectController.js';
import { protect, authorize } from '../middleware/authMiddleware.js';
const router = Router();
router.get('/', controller.list);
router.get('/slug/:slug', controller.getBySlug);
router.get('/:id', controller.get);
router.post('/', protect, authorize('admin'), controller.create);
router.put('/:id', protect, authorize('admin'), controller.update);
router.delete('/:id', protect, authorize('admin'), controller.remove);
export default router;
